"""initial

Revision ID: b56f8d457ae1
Revises: 
Create Date: 2026-02-28 16:34:05.830753

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b56f8d457ae1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("transaction_kinds",
    sa.Column("name", sa.String(length=50), nullable=False),
    sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_transaction_kinds_name"), "transaction_kinds", ["name"], unique=True)
    op.create_table("users",
    sa.Column("name", sa.String(length=200), nullable=False),
    sa.Column("email", sa.String(length=320), nullable=False),
    sa.Column("phone", sa.String(length=50), nullable=True),
    sa.Column("password_hash", sa.Text(), nullable=False),
    sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("phone")
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table("accounts",
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("name", sa.String(length=200), nullable=False),
    sa.Column("account_type", sa.String(length=50), nullable=False),
    sa.Column("opening_balance", sa.Numeric(precision=12, scale=2), server_default=sa.text("0"), nullable=False),
    sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("user_id", "name", name="uq_accounts_user_name")
    )
    op.create_index("ix_accounts_user_id", "accounts", ["user_id"], unique=False)
    op.create_table("budgets",
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("name", sa.String(length=200), nullable=False),
    sa.Column("period_start", sa.Date(), nullable=False),
    sa.Column("period_end", sa.Date(), nullable=False),
    sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("user_id", "period_start", "period_end", name="uq_budgets_user_period")
    )
    op.create_index("ix_budgets_user_period", "budgets", ["user_id", "period_start", "period_end"], unique=False)
    op.create_table("categories",
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("name", sa.String(length=120), nullable=False),
    sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("user_id", "name", name="uq_categories_user_name")
    )
    op.create_index("ix_categories_user_id", "categories", ["user_id"], unique=False)
    op.create_table("budget_items",
    sa.Column("budget_id", sa.UUID(), nullable=False),
    sa.Column("category_id", sa.UUID(), nullable=False),
    sa.Column("limit_amount", sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
    sa.CheckConstraint("limit_amount >= 0", name="ck_budget_items_limit_nonneg"),
    sa.ForeignKeyConstraint(["budget_id"], ["budgets.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="RESTRICT"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("budget_id", "category_id", name="uq_budget_items_budget_category")
    )
    op.create_index("ix_budget_items_budget_id", "budget_items", ["budget_id"], unique=False)
    op.create_table("recurring_transactions",
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("kind_id", sa.UUID(), nullable=False),
    sa.Column("account_id", sa.UUID(), nullable=False),
    sa.Column("to_account_id", sa.UUID(), nullable=True),
    sa.Column("category_id", sa.UUID(), nullable=True),
    sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column("description", sa.Text(), nullable=True),
    sa.Column("cadence", sa.String(length=30), nullable=False),
    sa.Column("next_run_date", sa.Date(), nullable=False),
    sa.Column("end_date", sa.Date(), nullable=True),
    sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
    sa.CheckConstraint("(to_account_id IS NULL) OR (account_id <> to_account_id)", name="ck_recurring_not_self_transfer"),
    sa.CheckConstraint("amount >= 0", name="ck_recurring_amount_nonneg"),
    sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="RESTRICT"),
    sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="RESTRICT"),
    sa.ForeignKeyConstraint(["kind_id"], ["transaction_kinds.id"], ondelete="RESTRICT"),
    sa.ForeignKeyConstraint(["to_account_id"], ["accounts.id"], ondelete="RESTRICT"),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index("ix_recurring_user_next_run", "recurring_transactions", ["user_id", "next_run_date"], unique=False)
    op.create_table("transactions",
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("kind_id", sa.UUID(), nullable=False),
    sa.Column("account_id", sa.UUID(), nullable=False),
    sa.Column("to_account_id", sa.UUID(), nullable=True),
    sa.Column("category_id", sa.UUID(), nullable=True),
    sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column("description", sa.Text(), nullable=True),
    sa.Column("posted_at", sa.Date(), nullable=False),
    sa.Column("refunded_transaction_id", sa.UUID(), nullable=True),
    sa.Column("transfer_group_id", sa.UUID(), nullable=True),
    sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
    sa.CheckConstraint("(to_account_id IS NULL) OR (account_id <> to_account_id)", name="ck_transactions_not_self_transfer"),
    sa.CheckConstraint("amount >= 0", name="ck_transactions_amount_nonneg"),
    sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="RESTRICT"),
    sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="RESTRICT"),
    sa.ForeignKeyConstraint(["kind_id"], ["transaction_kinds.id"], ondelete="RESTRICT"),
    sa.ForeignKeyConstraint(["refunded_transaction_id"], ["transactions.id"], ondelete="RESTRICT"),
    sa.ForeignKeyConstraint(["to_account_id"], ["accounts.id"], ondelete="RESTRICT"),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index("ix_transactions_kind_id", "transactions", ["kind_id"], unique=False)
    op.create_index("ix_transactions_user_account_posted_at", "transactions", ["user_id", "account_id", "posted_at"], unique=False)
    op.create_index("ix_transactions_user_category_posted_at", "transactions", ["user_id", "category_id", "posted_at"], unique=False)
    op.create_index("ix_transactions_user_posted_at", "transactions", ["user_id", "posted_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transactions_user_posted_at", table_name="transactions")
    op.drop_index("ix_transactions_user_category_posted_at", table_name="transactions")
    op.drop_index("ix_transactions_user_account_posted_at", table_name="transactions")
    op.drop_index("ix_transactions_kind_id", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index("ix_recurring_user_next_run", table_name="recurring_transactions")
    op.drop_table("recurring_transactions")
    op.drop_index("ix_budget_items_budget_id", table_name="budget_items")
    op.drop_table("budget_items")
    op.drop_index("ix_categories_user_id", table_name="categories")
    op.drop_table("categories")
    op.drop_index("ix_budgets_user_period", table_name="budgets")
    op.drop_table("budgets")
    op.drop_index("ix_accounts_user_id", table_name="accounts")
    op.drop_table("accounts")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_transaction_kinds_name"), table_name="transaction_kinds")
    op.drop_table("transaction_kinds")
    # ### end Alembic commands ###
